---
language: perl
perl:
  - "5.18"
script: make test

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - cpanm Exception::Class

branches:
  only:
  - master
  - staging
  - develop
  - dev
