---
language: perl
perl:
  - "5.18"
script: make test

install:
  - cpan-install Exception::Class --deps
  - cpan-install JSON::RPC::Client --deps

branches:
  only:
  - master
  - staging
  - develop
  - dev
